'@react95/clippy':
  - changed-files:
      - any-glob-to-any-file: 'packages/clippy/**/*'

'@react95/core':
  - changed-files:
      - any-glob-to-any-file: 'packages/core/**/*'

'@react95/cra-template':
  - changed-files:
      - any-glob-to-any-file: 'packages/cra-template/**/*'

'@react95/cra-template-typescript':
  - changed-files:
      - any-glob-to-any-file: 'packages/cra-template-typescript/**/*'

'@react95/design':
  - changed-files:
      - any-glob-to-any-file: 'packages/design/**/*'

'@react95/icons':
  - changed-files:
      - any-glob-to-any-file: 'packages/icons/**/*'
