name: React95 - Bojagi build workflow

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Configure CI Git User
        run: |
          git remote set-url origin https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config --global user.email ggdaltoso@gmail.com
          git config --global user.name ggdaltoso
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: yarn --pure-lockfile --non-interactive

      - name: Build
        run: |
          yarn build:bojagi

      - uses: actions/upload-artifact@v2
        with:
          name: bojagi
          path: ./packages/core/.bojagi/tmp
