#!/bin/bash

BRANCH=`git rev-parse --abbrev-ref HEAD`
echo "on branch $BRANCH"

set -e

if [[ $BRANCH == "master" ]];
then
  yarn nx release --yes
elif [[ $BRANCH == "alpha" ]];
then
  yarn nx release --preid=alpha --yes
  yarn nx release publish --tag=alpha
else
  echo "Nothing to publish on branch $BRANCH..."
fi
