name: Labeler
on: [pull_request_target]

permissions: read-all

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@v6
        with:
          repo-token: '${{ secrets.GH_TOKEN }}'
          sync-labels: true
